services:
  fossflow:
    image: abrar74774/fossflow:latest
    pull_policy: always
    ports:
      - 80:80
    environment:
      - NODE_ENV=production
      - ENABLE_SERVER_STORAGE=${ENABLE_SERVER_STORAGE:-true}
      - STORAGE_PATH=/data/diagrams
      - ENABLE_GIT_BACKUP=${ENABLE_GIT_BACKUP:-false}
      - HTTP_AUTH_USER=${HTTP_AUTH_USER:-}
      - HTTP_AUTH_PASSWORD=${HTTP_AUTH_PASSWORD:-}
      - PUID=${PUID:-}
      - PGID=${PGID:-}
    volumes:
      - ./diagrams:/data/diagrams
